//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diziyorum
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICI
    {
        public int ID { get; set; }
        public string KULLANICIADI { get; set; }
        public string SIFRE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> KULLANICIYORUM { get; set; }
        public int KULLANICITIP { get; set; }
    
        public virtual TBLYORUM TBLYORUM { get; set; }
    }
}
